export const SET_LOGIN_STATE = "SET_LOGIN_STATE"
export const SET_LOGOUT_STATE = "SET_LOGOUT_STATE"
export const PUSH_NOTIFICATIONS= "PUSH_NOTIFICATIONS"
export const SET_LOADING= 'SET_LOADING'
export const SET_INITIAL_LOADING= 'SET_INITIAL_LOADING'
export const RETRIEVE_TOKEN= 'RETRIEVE_TOKEN'
export const FCM_TOKEN= 'FCM_TOKEN'
